# Generated by Django 3.2.15 on 2022-10-25 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20221014_0924'),
        ('user', '0002_user_token'),
    ]

    operations = [
    ]
